# Generated by Django 3.1.7 on 2021-03-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(default=0, max_length=1000),
        ),
    ]
